name: CI
on:
  workflow_dispatch:  
jobs:
  dispatch:
    uses: SouthCoded/Workflow-Research/.github/workflows/prod_work.yml@main
    with:
            ENVIRONMENT: prod
        secrets:
            MY_SECRET: ${{ secrets.PROD_ENV_REPO_SECRET }}
